# gltest configuration for TRIBUNE.
networks:
  default: testnetBradbury
  testnetBradbury:
    url: https://rpc-bradbury.genlayer.com

paths:
  contracts: contracts
  artifacts: artifacts

environment: .env
